##################### Solr-fabric Configuration Example #####################

# This file contains an overview of various configuration settings



#################################### Node #####################################
"solr.hosts" : ["logstash@192.168.0.174", "logstash@192.168.0.176"]

"dataset.hosts" : ["logstash@192.168.0.174", "logstash@192.168.0.176"]
"dataset.hosts.password" : "hello.logstash"


#################################### Paths ####################################

"path.data" : "/home/logstash/snowdrop/snowdrop-load-example"
"path.data.dir" : "data"
"path.source" : [{'./_source200' : 'logstash@192.168.0.174'}, {'./_source200' : 'logstash@192.168.0.176'}]